### PR TITLE
Fix issue #61 feature request:

### LINKED ISSUE #61: Feature request: quit after all windows are closed
A lot of applications offer an option to quit the application when the last window/file is closed. I personally prefer this over keeping the application open, especially if it's a lightweight app such as TableTool.

### PR DESCRIPTION
**Pull request by redcapua**
Fix issue #61 feature request:

Feature request: quit after all windows are closed #61

To activate featire check in menu 
Window -> Quit application on last window close

quit application on last window close

### CODE REVIEW

**Comment by jakob** [comment]
Thanks a lot for the Pull Request, but I am not going to merge this. As per discussion in issue #61, pretty much no other Mac App has this, so I don't think we should add that either.

**Comment by redcapua** [comment]
Hi!

@jakob 

Your point of view is pretty clear for me.
I will appreciate you merge my other pull requests.

P.S. I have done it especially for @stefandesu . He asked for this feature so he can fork my branch to have it.

**Comment by stefandesu** [comment]
Hi @redcapua, thank you so much for adding the feature! I tried it out, but unfortunately the option does not persist after the application quits. Is there an easy fix for that? Sorry to bother you even more. 🙈

**Comment by redcapua** [comment]
Hi @stefandesu 

I will add feature to save option value.
I guess it will in ~2 weeks due to my traveling....

**Comment by redcapua** [comment]
Hi!

@stefandesu requested feature added :)

**Pull request closed without merging**
